# Generated by Django 5.1.6 on 2025-02-22 15:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Rollno', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{4}-\\d{2}-\\d{3}-\\d{3}$')])),
                ('Year', models.PositiveIntegerField(verbose_name=django.core.validators.MaxValueValidator(4))),
                ('Branch', models.CharField(max_length=30)),
                ('Password', models.DateField()),
            ],
        ),
    ]
