# Generated by Django 5.1.6 on 2025-02-24 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P1', '0004_subject_subject_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='P1.sem'),
            preserve_default=False,
        ),
    ]
