# Generated by Django 5.1.6 on 2025-02-24 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P1', '0006_student_semester_alter_notifications_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Semester',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(8)]),
        ),
    ]
