# Generated by Django 5.1.6 on 2025-03-01 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P1', '0007_alter_student_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='P1.notifications')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='P1.student')),
                ('subjects', models.ManyToManyField(to='P1.subject')),
            ],
        ),
    ]
